/**
 * Owner admin auth public exports.
 */
export { AuthDomainError } from './errors.js';
export type { AuthErrorCode } from './errors.js';
export {
  generateClaimCode,
  generateOpaqueToken,
  hashClaimCode,
  hashIp,
  hashRefreshToken,
  hashSessionSecret,
  redactSensitive,
  safeEqualString,
  sha256Hex,
  summarizeUserAgent,
} from './crypto.js';
export {
  ADMIN_REAUTH_MAX_AGE_MS,
  ADMIN_SESSION_ABSOLUTE_TTL_MS,
  ADMIN_SESSION_IDLE_TTL_MS,
  generateAdminSessionToken,
  hashAdminSessionToken,
} from './admin-session-token.js';
export {
  OWNER_ADMIN_AUTH_OPERATIONAL_CONFIRM,
  OWNER_ADMIN_AUTH_MAX_FAILURES,
  OWNER_ADMIN_AUTH_FAILURE_WINDOW_MS,
  OWNER_ADMIN_AUTH_LOCKOUT_MS,
  assertNoUnsupportedActiveCredentials,
  assertOperationalFirstEnrollmentAllowed,
  assertOwnerAdminAuthDatabaseWritable,
  assertOwnerAuthOperationalDefaultDeny,
  beginOwnerAdminTotpEnrollment,
  completeOwnerAdminTotpEnrollment,
  generateTotpCode,
  isAdminSessionReauthFresh,
  isPool,
  loginOwnerAdmin,
  logoutOwnerAdminSession,
  preflightOwnerAdminEnrollment,
  reauthenticateOwnerAdminSession,
  requireOwnerAuthPool,
  verifyOwnerAdminPasswordAndTotp,
  withPinnedOwnerAuthTransaction,
  withPoolOwnedOwnerAuthTransaction,
  withPoolOwnedReadOnlyTransaction,
} from './admin-auth.js';
export type {
  EnrollOwnerAdminFactorsResult,
  LoginOwnerAdminBundle,
  LoginOwnerAdminInput,
  LoginOwnerAdminResult,
  OwnerAdminAuthDatabaseGate,
  ReauthOwnerAdminSessionInput,
  ReauthOwnerAdminSessionResult,
} from './admin-auth.js';
export {
  ADMIN_TOTP_DIGITS,
  ADMIN_TOTP_PERIOD_SECONDS,
  buildOtpAuthUri,
  totpStepAt,
  verifyTotpCode,
  verifyTotpCodeWithStep,
} from './admin-totp.js';
export {
  assertInteractiveSecretTerminals,
  displaySecretOnceOnInteractiveStderr,
  readSecretFromTty,
} from './tty-secret.js';
export { issueAccessToken, verifyAccessToken, type AccessTokenClaims } from './access-token.js';
export {
  assertSessionActive,
  createUserSession,
  listActiveSessions,
  revokeAllUserSessions,
  revokeSession,
  rotateRefreshSession,
  type RequestMeta,
  type SessionConfig,
  type SessionRevocationReason,
  type SessionTokens,
} from './sessions.js';
export {
  authenticateWithTelegramInitData,
  type AuthenticatedUser,
  type PreferredLocale,
  type TelegramLoginResult,
} from './telegram-login.js';
export {
  claimFounderCode,
  getFounderHistory,
  getMembershipView,
  grantFounderMembership,
  issueFounderClaimCode,
  reassignFounderMembership,
  searchFounderMember,
  type FounderClaimCodeIssueResult,
  type FounderClaimResult,
  type FounderGrantResult,
  type FounderHistoryView,
  type FounderSearchHit,
  type MembershipView,
} from './membership.js';
export { consumeThrottle, type ThrottlePolicy } from './throttle.js';
export {
  abortOwnerBootstrapAttempt,
  assertBootstrapTlsAndEndpoint,
  assertPoolBoundBootstrapTrust,
  buildChannelPopBytes,
  buildFinalCredBytes,
  buildIsolatedTestEndpointProfile,
  bootstrapEndpointProfileFromCeremonyWire,
  buildOwnerBootstrapPoolConfig,
  buildOwnerChallengeBytes,
  buildTestGrantPayload,
  canonicalizeToJcs,
  ceremonyWireFromBootstrapEndpointProfile,
  clearIsolatedTestBootstrapClock,
  completeOwnerBootstrapEnrollment,
  createBootstrapTrustMaterial,
  createEnrollmentChannelKeypair,
  createEphemeralCeremonyAuthority,
  createOwnerBootstrapPool,
  digestCeremonyEndpointProfileV1,
  digestCeremonySealV1,
  generateTotpSecretBytes,
  parseAndVerifyGrantEnvelope,
  parseCeremonyEndpointProfileV1Json,
  parseCeremonySealV1Json,
  parseStrictJson,
  setIsolatedTestBootstrapClock,
  signChannelAbort,
  signChannelPop,
  signFinalCredReq,
  signGrantEnvelope,
  signOwnerRedeemChallenge,
  startOwnerBootstrapAttempt,
  submitOwnerBootstrapPop,
  validateCeremonyEndpointProfileV1,
  validateCeremonySealV1,
  assertSealProfileDigestMatchesProfile,
  assertDerivativeConsistentWithProfile,
  assertDerivativeDigestEqualsRecordedSealDigest,
  claimDerivativeProvenanceAuthenticated,
  parseDeploymentTrustDerivativeV1Json,
  refuseSameHostChecksumAsChannelB,
  validateDeploymentTrustDerivativeV1,
  G5_SPKI_V1_DECISION,
  assertSpkiPinningUnsupportedForV1,
  buildVerifyFullTlsSocketOptions,
  CEREMONY_ENDPOINT_PROFILE_DIGEST_METHOD,
  CEREMONY_SEAL_PROVENANCE_CHANNEL_B_V1,
  DEPLOYMENT_TRUST_DERIVATIVE_KIND_V1,
  type BootstrapConnectionFacts,
  type BootstrapEndpointProfile,
  type BootstrapTrustMaterial,
  type CeremonyAuthority,
  type CeremonyEndpointProfileV1,
  type CeremonySealV1,
  type DeploymentTrustDerivativeV1,
  type OwnerBootstrapGrantEnvelope,
  type OwnerBootstrapPool,
} from './owner-bootstrap/index.js';
