/**
 * Owner admin auth public exports.
 */
export { AuthDomainError } from './errors.js';
export type { AuthErrorCode } from './errors.js';
export {
  generateClaimCode,
  generateOpaqueToken,
  hashClaimCode,
  hashIp,
  hashRefreshToken,
  hashSessionSecret,
  redactSensitive,
  safeEqualString,
  sha256Hex,
  summarizeUserAgent,
} from './crypto.js';
export {
  ADMIN_REAUTH_MAX_AGE_MS,
  ADMIN_SESSION_ABSOLUTE_TTL_MS,
  ADMIN_SESSION_IDLE_TTL_MS,
  generateAdminSessionToken,
  hashAdminSessionToken,
} from './admin-session-token.js';
export {
  OWNER_ADMIN_AUTH_OPERATIONAL_CONFIRM,
  OWNER_ADMIN_AUTH_MAX_FAILURES,
  OWNER_ADMIN_AUTH_FAILURE_WINDOW_MS,
  OWNER_ADMIN_AUTH_LOCKOUT_MS,
  assertNoUnsupportedActiveCredentials,
  assertOperationalFirstEnrollmentAllowed,
  assertOwnerAdminAuthDatabaseWritable,
  assertOwnerAuthOperationalDefaultDeny,
  beginOwnerAdminTotpEnrollment,
  completeOwnerAdminTotpEnrollment,
  generateTotpCode,
  isAdminSessionReauthFresh,
  isPool,
  loginOwnerAdmin,
  logoutOwnerAdminSession,
  preflightOwnerAdminEnrollment,
  reauthenticateOwnerAdminSession,
  requireOwnerAuthPool,
  verifyOwnerAdminPasswordAndTotp,
  withPinnedOwnerAuthTransaction,
  withPoolOwnedOwnerAuthTransaction,
  withPoolOwnedReadOnlyTransaction,
} from './admin-auth.js';
export type {
  EnrollOwnerAdminFactorsResult,
  LoginOwnerAdminBundle,
  LoginOwnerAdminInput,
  LoginOwnerAdminResult,
  OwnerAdminAuthDatabaseGate,
  ReauthOwnerAdminSessionInput,
  ReauthOwnerAdminSessionResult,
} from './admin-auth.js';
export {
  ADMIN_WEBAUTHN_CHALLENGE_TTL_MS,
  beginWebAuthnAuthentication,
  beginWebAuthnReauth,
  beginWebAuthnRegistration,
  finishWebAuthnAuthentication,
  finishWebAuthnReauth,
  finishWebAuthnRegistration,
  peekWebAuthnChallengeForTests,
  resolveAdminWebAuthnRpConfig,
} from './admin-webauthn.js';
export type {
  AdminWebAuthnChallengePurpose,
  AdminWebAuthnCredentialRow,
  AdminWebAuthnRpConfig,
  BeginWebAuthnAuthenticationResult,
  BeginWebAuthnRegistrationResult,
  FinishWebAuthnAuthenticationBundle,
  FinishWebAuthnAuthenticationResult,
  FinishWebAuthnRegistrationResult,
} from './admin-webauthn.js';
export {
  ADMIN_RECOVERY_CODE_BYTE_LENGTH,
  ADMIN_RECOVERY_CODE_COUNT,
  consumeRecoveryCode,
  formatRecoveryCodeForDisplay,
  generateRecoveryCodes,
  hashAdminRecoveryCode,
  normalizeRecoveryCode,
  rotateRecoveryCodes,
} from './admin-recovery.js';
export type {
  ConsumeRecoveryCodeBundle,
  ConsumeRecoveryCodeResult,
  GenerateRecoveryCodesResult,
} from './admin-recovery.js';
export {
  assertAdminOwnerRole,
  assertRecentReauth,
  beginLoginViaWebAuthn,
  beginReauthViaWebAuthn,
  loginViaPasswordTotp,
  loginViaRecoveryCode,
  loginViaWebAuthn,
  looksLikeTelegramUserAccessToken,
  reauthViaPasswordTotp,
  reauthViaWebAuthn,
  verifyAdminSessionToken,
} from './admin-http.js';
export type { VerifiedAdminSession } from './admin-http.js';
export {
  ADMIN_WEB_CONFIRMATION_ACTION_PREFIXES,
  ADMIN_WEB_CONFIRMATION_TTL_MS,
  canonicalizeAdminWebPayload,
  confirmAdminWebConfirmation,
  consumeAdminWebConfirmation,
  digestAdminWebPayload,
  isAllowedAdminWebConfirmationAction,
  prepareAdminWebConfirmation,
} from './admin-web-confirmations.js';
export type {
  ConfirmAdminWebConfirmationInput,
  ConfirmAdminWebConfirmationResult,
  ConsumeAdminWebConfirmationInput,
  ConsumeAdminWebConfirmationResult,
  PrepareAdminWebConfirmationInput,
  PrepareAdminWebConfirmationResult,
} from './admin-web-confirmations.js';
export {
  ADMIN_TOTP_DIGITS,
  ADMIN_TOTP_PERIOD_SECONDS,
  buildOtpAuthUri,
  totpStepAt,
  verifyTotpCode,
  verifyTotpCodeWithStep,
} from './admin-totp.js';
export {
  assertInteractiveSecretTerminals,
  displaySecretOnceOnInteractiveStderr,
  readSecretFromTty,
} from './tty-secret.js';
export { issueAccessToken, verifyAccessToken, type AccessTokenClaims } from './access-token.js';
export {
  assertSessionActive,
  createUserSession,
  listActiveSessions,
  revokeAllUserSessions,
  revokeSession,
  rotateRefreshSession,
  type RequestMeta,
  type SessionConfig,
  type SessionRevocationReason,
  type SessionTokens,
} from './sessions.js';
export {
  authenticateWithTelegramInitData,
  type AuthenticatedUser,
  type PreferredLocale,
  type TelegramLoginReferralResult,
  type TelegramLoginResult,
} from './telegram-login.js';
export {
  claimFounderCode,
  getFounderHistory,
  getMembershipView,
  grantFounderMembership,
  issueFounderClaimCode,
  reassignFounderMembership,
  searchFounderMember,
  type FounderClaimCodeIssueResult,
  type FounderClaimResult,
  type FounderGrantResult,
  type FounderHistoryView,
  type FounderSearchHit,
  type MembershipView,
} from './membership.js';
export { consumeThrottle, type ThrottlePolicy } from './throttle.js';
export {
  abortOwnerBootstrapAttempt,
  assertBootstrapTlsAndEndpoint,
  assertPoolBoundBootstrapTrust,
  buildChannelPopBytes,
  buildFinalCredBytes,
  buildIsolatedTestEndpointProfile,
  bootstrapEndpointProfileFromCeremonyWire,
  buildOwnerBootstrapPoolConfig,
  buildOwnerChallengeBytes,
  buildTestGrantPayload,
  canonicalizeToJcs,
  ceremonyWireFromBootstrapEndpointProfile,
  clearIsolatedTestBootstrapClock,
  completeOwnerBootstrapEnrollment,
  createBootstrapTrustMaterial,
  createEnrollmentChannelKeypair,
  createEphemeralCeremonyAuthority,
  createOwnerBootstrapPool,
  digestCeremonyEndpointProfileV1,
  digestCeremonySealV1,
  generateTotpSecretBytes,
  parseAndVerifyGrantEnvelope,
  parseCeremonyEndpointProfileV1Json,
  parseCeremonySealV1Json,
  parseStrictJson,
  setIsolatedTestBootstrapClock,
  signChannelAbort,
  signChannelPop,
  signFinalCredReq,
  signGrantEnvelope,
  signOwnerRedeemChallenge,
  startOwnerBootstrapAttempt,
  submitOwnerBootstrapPop,
  validateCeremonyEndpointProfileV1,
  validateCeremonySealV1,
  assertSealProfileDigestMatchesProfile,
  assertDerivativeConsistentWithProfile,
  assertDerivativeDigestEqualsRecordedSealDigest,
  claimDerivativeProvenanceAuthenticated,
  parseDeploymentTrustDerivativeV1Json,
  refuseSameHostChecksumAsChannelB,
  validateDeploymentTrustDerivativeV1,
  G5_SPKI_V1_DECISION,
  assertSpkiPinningUnsupportedForV1,
  buildVerifyFullTlsSocketOptions,
  CEREMONY_ENDPOINT_PROFILE_DIGEST_METHOD,
  CEREMONY_SEAL_PROVENANCE_CHANNEL_B_V1,
  DEPLOYMENT_TRUST_DERIVATIVE_KIND_V1,
  ISOLATED_OWNER_CEREMONY_TARGET,
  ISOLATED_TELEGRAM_OWNER_BOOTSTRAP_TARGET,
  assertConfiguredOwnerTelegramUserId,
  assertConnectionUrlAllowedForIsolatedCeremony,
  assertIsolatedCeremonyAllowsEnrollment,
  assertIsolatedTelegramOwnerBootstrapTarget,
  assertWitnessesAreConcrete,
  buildIsolatedCeremonyEndpointProfileV1,
  buildIsolatedCeremonyGrantPayload,
  digestIsolatedCeremonyEndpointProfileV1,
  draftCeremonySeal,
  enrollIsolatedTelegramOwner,
  generateEphemeralCeremonyKeypairFiles,
  loadCeremonyAuthorityFromDir,
  openIsolatedCeremonyBootstrap,
  parseIsolatedOwnerBootstrapUrl,
  recordChannelBDigestFromOwner,
  runIsolatedOptionCEnrollment,
  verifyOwnerTelegramIdentityForBootstrap,
  writeIsolatedCeremonyProfile,
  type BootstrapConnectionFacts,
  type BootstrapEndpointProfile,
  type BootstrapTrustMaterial,
  type CeremonyAuthority,
  type CeremonyEndpointProfileV1,
  type CeremonySealV1,
  type DeploymentTrustDerivativeV1,
  type IsolatedCeremonyEndpointProfileV1,
  type IsolatedTelegramOwnerBootstrapResult,
  type OwnerBootstrapGrantEnvelope,
  type OwnerBootstrapPool,
  authenticateProductionCeremonyFromOwnerTty,
  assertAuthenticatedProductionBootstrapTrust,
  isAuthenticatedProductionBootstrapTrust,
  startProductionOwnerBootstrapAttempt,
  submitProductionOwnerBootstrapPop,
  abortProductionOwnerBootstrapAttempt,
  completeProductionOwnerBootstrapEnrollment,
  orchestrateProductionOwnerBootstrapCeremony,
  assertProductionCeremonyApplyGates,
  validateProductionCeremonyBundleStructurally,
  generateProductionBootstrapKeypairFiles,
  buildProductionOwnerBootstrapReadinessReport,
  preflightProductionOwnerBootstrapSchema,
  REQUIRED_PRODUCTION_OWNER_BOOTSTRAP_MIGRATIONS,
  resolvePublicProxyDialIps,
  discoverProductionTrustedEndpoint,
  runProductionOwnerBootstrapPreflightOnly,
  runAuthenticatedProductionOwnerBootstrapPreflightOnly,
  hydrateIntendedExistingAdminBindingFromDatabase,
  inspectExistingAdminAuthMaterial,
  type AuthenticatedProductionCeremonySession,
  type HydrateIntendedExistingAdminResult,
  type AuthenticatedProductionBootstrapTrust,
  type ProductionCeremonyBundleV1,
  type ProductionTrustedEndpointDiscoveryInput,
  type ProductionTrustedEndpointDiscoveryResult,
  type ProductionOwnerBootstrapPreflightOnlyResult,
  type ClaimExistingAdminAuthCounts,
} from './owner-bootstrap/index.js';
