/** CSS custom-property names for ALEx Rewards design tokens. */
export const tokenNames = {
  bg: '--alex-bg',
  surface: '--alex-surface',
  surfaceElevated: '--alex-surface-elevated',
  text: '--alex-text',
  textSecondary: '--alex-text-secondary',
  border: '--alex-border',
  accent: '--alex-accent',
  success: '--alex-success',
  warning: '--alex-warning',
  error: '--alex-error',
  space1: '--alex-space-1',
  space2: '--alex-space-2',
  space3: '--alex-space-3',
  space4: '--alex-space-4',
  space5: '--alex-space-5',
  space6: '--alex-space-6',
  space8: '--alex-space-8',
  space10: '--alex-space-10',
  space12: '--alex-space-12',
  radiusSm: '--alex-radius-sm',
  radiusMd: '--alex-radius-md',
  radiusLg: '--alex-radius-lg',
  radiusXl: '--alex-radius-xl',
  radiusFull: '--alex-radius-full',
  shadowSm: '--alex-shadow-sm',
  shadowMd: '--alex-shadow-md',
  shadowLg: '--alex-shadow-lg',
  focusRing: '--alex-focus-ring',
  bgRadial: '--alex-bg-radial',
} as const;

export type TokenName = (typeof tokenNames)[keyof typeof tokenNames];

/** Convenience `var(--alex-*)` references for inline style usage. */
export const tokens = {
  bg: `var(${tokenNames.bg})`,
  surface: `var(${tokenNames.surface})`,
  surfaceElevated: `var(${tokenNames.surfaceElevated})`,
  text: `var(${tokenNames.text})`,
  textSecondary: `var(${tokenNames.textSecondary})`,
  border: `var(${tokenNames.border})`,
  accent: `var(${tokenNames.accent})`,
  success: `var(${tokenNames.success})`,
  warning: `var(${tokenNames.warning})`,
  error: `var(${tokenNames.error})`,
  space1: `var(${tokenNames.space1})`,
  space2: `var(${tokenNames.space2})`,
  space3: `var(${tokenNames.space3})`,
  space4: `var(${tokenNames.space4})`,
  space5: `var(${tokenNames.space5})`,
  space6: `var(${tokenNames.space6})`,
  space8: `var(${tokenNames.space8})`,
  space10: `var(${tokenNames.space10})`,
  space12: `var(${tokenNames.space12})`,
  radiusSm: `var(${tokenNames.radiusSm})`,
  radiusMd: `var(${tokenNames.radiusMd})`,
  radiusLg: `var(${tokenNames.radiusLg})`,
  radiusXl: `var(${tokenNames.radiusXl})`,
  radiusFull: `var(${tokenNames.radiusFull})`,
  shadowSm: `var(${tokenNames.shadowSm})`,
  shadowMd: `var(${tokenNames.shadowMd})`,
  shadowLg: `var(${tokenNames.shadowLg})`,
  focusRing: `var(${tokenNames.focusRing})`,
  bgRadial: `var(${tokenNames.bgRadial})`,
} as const;
